name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@30c518dd8396e860f25ca4295dc6f4cd4a09b1da
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
